### ISSUE TITLE
Check formulas for overlap

### ISSUE THREAD

**Issue by oracleofnj** [ExtendLang/Extend#95]
throw an error on variable instantiation if multiple formulas assigned to same cell e.g. foo[0,0] = 1; foo[0,0] = 2; OR foo[0:3,0:3]=x; foo[2,2] = y;

**Comment by Neitsch** [comment]
Should the program display a warning and evaluate the first (or last) defined formula, or exit without further questions. I could see that people would like to assign a different formula past a certain point in all directions, e.g.
tmp[5,5];
[:2,:2]tmp = 3;
[0:,0:]tmp = 5;

Otherwise they need to write
tmp[5,5];
[:2,:2]tmp = 3;
[2:,0:]tmp = 5;
[:2,2:]tmp = 5;

However I agree that throwing an error is probably the right way to go about it, just want to throw an idea out there.

**Comment by oracleofnj** [comment]
Exit unceremoniously. One formula per cell.

**Comment by oracleofnj** [comment]
BTW working on a bug right now. You can see in more-stdlib-functions; look
at samples/triangular.xtnd

**Comment by oracleofnj** [comment]
Addresed by https://github.com/ExtendLang/Extend/pull/104
